### ISSUE TITLE
Wallpapers request

### ISSUE THREAD

**Issue by M2ck** [Papuh/PapuhWalls#29]
Great job done on this app, thank a lot :+1:
Could you add [CM Material Wallpapers] (https://github.com/CyanogenMod/android_packages_apps_CMWallpapers/commit/b684222ef59ab60f92b5e047b2eafacf46b89678) and [Google Now Original Wallpapers] (http://www.droidviews.com/download-hd-quality-google-now-wallpapers-for-your-android-device-and-desktop/)?

**Comment by Mazda--** [comment]
Make a pull request here for those wallpapers and I'll review them
https://github.com/DirtyUnicorns/Papuh-Resources

**Comment by M2ck** [comment]
I'm not a developer (only a translator), I don't know make such pull request. So it will be better to send this in Issues tab like here no?
