### ISSUE TITLE
License of the app itself

### ISSUE THREAD

**Issue by krt16s** [Papuh/PapuhWalls#39]
Is the app itself CC-BY licensed or just for the wallpapers? Isn't Apache2 or GPLv3 a better choice for actual source code?

**Comment by martykan** [comment]
It seems like the whole app is CC-BY, since it's based on https://github.com/jahirfiquitiva/PaperBoard-Final

**Comment by krt16s** [comment]
You are right, paper-board's wording is more clear, this applies to the whole app. Thanks for pointing out.
