### ISSUE TITLE
Picasso error when using huge wallpapers (Like Black and White #3)

### ISSUE THREAD

**Issue by jereksel** [Papuh/PapuhWalls#4]
Nexus 4, SlimLP

Logcat message:
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (4608x3072, max=4096x4096)

This could help:
https://stackoverflow.com/questions/10271020/bitmap-too-large-to-be-uploaded-into-a-texture

**Comment by Mazda--** [comment]
I think I have this one fixed, I'll hit you up on hangouts to test as I can't duplicate the issue
