### ISSUE TITLE
Many API used in your app not exist in SDK level 23.

### ISSUE THREAD

**Issue by jay2013** [Papuh/PapuhWalls#47]
Hi, we find that many API in package "org.apache.http.*" have been moved out since level 23, however, you called them in your codes. these API call  may cause your app crash on level 23 android machine.
we list these api call below, please help to check.
Thanks very much!

we notice that in your App's dex file(Version 2.0.6), it contains "org.apache.http" package, the class file seems to be empty. the class file is  only about 20 byte in size. we feel very curious about this.

Dongjie He

[Uploading com.alexcruz.papuhwalls_10.apk.report.txt…]()
 

all related Bugs are list here, please help to check.
Thanks very much.

com.alexcruz.papuhwalls_10.apk minSdkVersion: 14, maxSdkVersion: 23
BUG: <org.apache.http.util.EntityUtils: java.lang.String toString(org.apache.http.HttpEntity)> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 17 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

BUG: <org.apache.http.HttpResponse: org.apache.http.StatusLine getStatusLine()> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 16 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

BUG: <org.apache.http.util.EntityUtils: java.lang.String toString(org.apache.http.HttpEntity)> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 119 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 15 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

BUG: <org.apache.http.client.methods.HttpGet: void <init>(java.lang.String)> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 117 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <org.apache.http.impl.client.DefaultHttpClient: void <init>()> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 116 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <org.apache.http.HttpResponse: org.apache.http.StatusLine getStatusLine()> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 118 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <org.apache.http.client.methods.HttpGet: void <init>(java.lang.String)> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 15 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

BUG: <org.apache.http.StatusLine: int getStatusCode()> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 16 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

BUG: <org.apache.http.HttpResponse: org.apache.http.HttpEntity getEntity()> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 119 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 117 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <org.apache.http.impl.client.DefaultHttpClient: void <init>()> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 14 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

BUG: <org.apache.http.StatusLine: int getStatusCode()> called in <com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)> on line 118 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.ArtSource: void onTryUpdate(int)>
	--><com.alexcruz.papuhwalls.ArtSource: void getWallpapersFromUrl(java.lang.String)>

BUG: <java.util.zip.Deflater: int deflate(byte[],int,int,int)> called in <okio.DeflaterSink: void deflate(boolean)> on line 93 not in [16, 17, 18, 14, 15]
reachable path:
	--><com.alexcruz.papuhwalls.WallsFragment: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.WallsFragment$DownloadBitmap: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.WallsFragment$DownloadBitmap: android.net.Uri doInBackground(java.lang.Void[])>
	--><com.squareup.okhttp.Call: com.squareup.okhttp.Response execute()>
	--><com.squareup.okhttp.Call: com.squareup.okhttp.Response getResponseWithInterceptorChain(boolean)>
	--><com.squareup.okhttp.Call$ApplicationInterceptorChain: com.squareup.okhttp.Response proceed(com.squareup.okhttp.Request)>
	--><com.squareup.okhttp.Call: com.squareup.okhttp.Response getResponse(com.squareup.okhttp.Request,boolean)>
	--><com.squareup.okhttp.internal.http.HttpEngine: void sendRequest()>
	--><com.squareup.okhttp.internal.http.HttpEngine: void connect()>
	--><com.squareup.okhttp.internal.http.HttpEngine: com.squareup.okhttp.Connection nextConnection()>
	--><com.squareup.okhttp.OkHttpClient$1: void connectAndSetOwner(com.squareup.okhttp.OkHttpClient,com.squareup.okhttp.Connection,com.squareup.okhttp.internal.http.HttpEngine,com.squareup.okhttp.Request)>
	--><com.squareup.okhttp.Connection: void connectAndSetOwner(com.squareup.okhttp.OkHttpClient,java.lang.Object,com.squareup.okhttp.Request)>
	--><com.squareup.okhttp.Connection: void connect(int,int,int,com.squareup.okhttp.Request)>
	--><com.squareup.okhttp.Connection: void upgradeToTls(com.squareup.okhttp.Request,int,int)>
	--><com.squareup.okhttp.internal.spdy.SpdyConnection: void sendConnectionPreface()>
	--><com.squareup.okhttp.internal.spdy.Spdy3$Writer: void windowUpdate(int,long)>
	--><okio.RealBufferedSink: void flush()>
	--><okio.DeflaterSink: void flush()>
	--><okio.DeflaterSink: void deflate(boolean)>

BUG: <org.apache.http.HttpResponse: org.apache.http.HttpEntity getEntity()> called in <com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)> on line 17 not in [23]
reachable path:
	--><com.alexcruz.papuhwalls.MainActivity: void onCreate(android.os.Bundle)>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Object doInBackground(java.lang.Object[])>
	--><com.alexcruz.papuhwalls.MainActivity$SetupLW: java.lang.Void doInBackground(java.lang.Void[])>
	--><com.alexcruz.papuhwalls.JSONParser: org.json.JSONObject getJSONfromURL(java.lang.String)>

**Comment by Mazda--** [comment]
This project is no longer maintained.

**Comment by jay2013** [comment]
Can you tell me whether our report is right or wrong? we actually use our tool to check it, so we need your help to give marks to our tool. Thanks very much.
